"""
Django settings for onlinetest project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'djvtfq*00sh$io3f0u%+tyggvg9*fo%8i=!o@schkk!u&@0slh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#FILE_ROOT = os.path.join(BASE_DIR, "upload")
FILE_ROOT = "upload"

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'testsystem.apps.TestsystemConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'onlinetest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'onlinetest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
# STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# simpleui theme
SIMPLEUI_DEFAULT_THEME = 'layui.css'
SIMPLEUI_HOME_INFO = True
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_DEFAULT_ICON = True
SIMPLEUI_ICON = {
    # '单选题': 'fab fa-apple',
    # '单选题': 'fas fa-code',
    '多选题': "fa fa-book",
    "填空题": "fa fa-paint-brush",
    "班级学生": "fa fa-users",
    "成绩": "fa fa-graduation-cap",
    "试卷": "fa fa-tasks",
}
SIMPLEUI_LOGO ='http://sec.guet.edu.cn/themes/core/static/img/logo.png'
# SIMPLEUI_LOGIN_PARTICLES = True
import time
# SIMPLEUI_ANALYSIS = True
SIMPLEUI_CONFIG = {
    'system_keep': True,
    # 'menu_display': ['单选题', '多选题', '填空题', '动态菜单测试'],      # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
        {
        'name': '题目搜索',
        'icon': 'fas fa-search',
        'models': [{
            'name': 'Bing',
            'url': 'https://www.bing.com/',
            'icon': 'fas fa-search'
            }, {
            'name': 'Baidu',
            'url': 'https://www.baidu.com/',
            'icon': 'fa fa-paw'
        }]
    },  {
        'name': 'The Icons',
        'icon': 'fas fa-spinner',
        'url': 'https://fontawesome.com/v4.7.0/examples/'
    }, {
        'name': '动态菜单测试' ,
        'icon': 'fa fa-desktop',
        'models': [{
            'name': time.time(),
            'icon': 'far fa-surprise'
        }]
    },{
        'name': '学生成绩分析' ,  # 待扩展
        'icon': "fa fa-hourglass-half",
        'models': [{
            'name': "成绩波动情况-折线图",
            'icon': 'far fa-surprise',
            'url': ''
        },{
            'name': "丢分情况-饼状图",
            'icon': 'far fa-surprise',
            'url': ''
        },{
            'name': "成绩对比-柱状图",
            'icon': 'far fa-surprise',
            'url': ''
        }]
    },{
        'name': '爬虫技术爬取试题' ,  # 待扩展
        'icon': "fa fa-bug",
        'models': [{
            'name': "微信公众号爬取",
            'icon': 'far fa-surprise',
            'url': ''
        },{
            'name': "试题网站爬取",
            'icon': 'far fa-surprise',
            'url': ''
        }]
    }]
}